### ISSUE TITLE
IntegrityError at /client/save/

### ISSUE THREAD

**Issue by Niets** [CAEP-UnB/gestorpsi#21]
(1048, "Column 'client_id' cannot be null")
Request Method:	POST
Request URL:	http://127.0.0.1:8000/client/save/
Django Version:	1.4.2
Exception Type:	IntegrityError
Exception Value:	
(1048, "Column 'client_id' cannot be null")
Exception Location:	/home/niets/.virtualenvs/gestorpsi/local/lib/python2.7/site-packages/MySQLdb/connections.py in defaulterrorhandler, line 36
Python Executable:	/home/niets/.virtualenvs/gestorpsi/bin/python
Python Version:	2.7.6
Python Path:	
['/home/niets/Documents/MES/gestorpsi',
 '/home/niets/.virtualenvs/gestorpsi/lib/python2.7',
 '/home/niets/.virtualenvs/gestorpsi/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/niets/.virtualenvs/gestorpsi/lib/python2.7/lib-tk',
 '/home/niets/.virtualenvs/gestorpsi/lib/python2.7/lib-old',
 '/home/niets/.virtualenvs/gestorpsi/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/niets/.virtualenvs/gestorpsi/local/lib/python2.7/site-packages',
 '/home/niets/.virtualenvs/gestorpsi/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg-info',
 '/home/niets/.virtualenvs/gestorpsi/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg-info']
Server time:	Ter, 17 Mar 2015 14:54:43 -0300

POST
Variable	Value
maritalStatus	
u'3'
neighborhood	
u'input'
addressId	
u''
email_id	
u''
photo	
u''
site_id	
u''
birthForeignCountry	
u'32'
document_typeDocument	
u'1'
addressType	
u'1'
addressLine2	
u'lote2'
addressLine1	
u'Look Sky ourk'
foreignCountry	
u'33'
document_document	
u'12345'
im_id	
u''
city	
u'1632'
foreignCity	
u''
area	
u'51'
site_description	
u'minha empresa'
comments	
u''
phoneNumber	
u'9999-99999'
phoneType	
u'4'
addressNumber	
u'15'
birthForeignState	
u'outlook'
save	
u'Salvar'
phoneId	
u''
foreignState	
u''
birthForeignCity	
u'hotmail'
zipCode	
u'716352'
nickname	
u'bill'
documentId	
u''
email_type	
u'2'
document_state	
u'3'
name	
u'bill'
dateBirth	
u'12/12/1991'
this	
u''
gender	
u'2'
document_issuer	
u'10'
im_identity	
u'billcat@hotmail.com'
ext	
u'+55'
site_site	
u'www.microsoft.com'
email_email	
u'bill@hotmali.com'
addressPrefix	
u'Sir'
im_network	
u'1'

**Comment by carloshfoliveira** [comment]
Please, try using a code paste service when registering an issue.

**Comment by carloshfoliveira** [comment]
About this bug, we pulled an updated version  of save client function, but it's broken. We're gonna rollback to the working one.
