### ISSUE TITLE
Update links to make them relatives

### ISSUE THREAD

**Issue by msfernandes** [caep-unb/gestorpsi#29]
Its better set relative links

**Comment by carloshfoliveira** [comment]
It's a know problem.

**Comment by carloshfoliveira** [comment]
I'd had a problem with this a while ago, it'd be good to fix it.

**Comment by carloshfoliveira** [comment]
Not only after register, there's a lot of hard coded links.

**Comment by carloshfoliveira** [comment]
http://paste.debian.net/304924/

**Comment by carloshfoliveira** [comment]
[egrep_output | uploaded via ZenHub](https://files.zenhub.io/55dcec3ac1081b130f470451)

**Comment by carloshfoliveira** [comment]
GestorPsi-MES/gestorpsi#2 is related to this one

**Comment by carloshfoliveira** [comment]
Both paste and file are output from an egrep command I executed to find gestorpsi.com.br direct references

**Comment by modestoo** [comment]
http://hackr.io/ tutorials

**Comment by carloshfoliveira** [comment]
Actually, it was supposed to be posted on our mailing list ;)

Em terça-feira, 25 de agosto de 2015, Augusto Modesto <
notifications@github.com> escreveu:

> http://hackr.io/ tutorials
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CAEP-UnB/gestorpsi/issues/29#issuecomment-134766935>.
>


-- 
Carlos Oliveira
LAPPIS - UnB/FGA(https://lappis.unb.br/)
GitHub: @carloshfoliveira <https://github.com/carloshfoliveira>
LinkedIn: @carloshenriquef <https://br.linkedin.com/in/carloshenriquef>
