### ISSUE TITLE
problemas ao levantar o ambiente

### ISSUE THREAD

**Issue by VictorArnaud** [caep-unb/gestorpsi#82]
No seguinte passo do Configuring project do arquivo INSTALL.md ao executar o comando:
`python creategroups.py na pasta script`
da o seguinte erro:
![erro1](https://cloud.githubusercontent.com/assets/14116020/16168310/2c2f7a70-34d9-11e6-91f0-06481eff9ebe.png)
Tentei usar o comando na pasta anterior a ela:
`python scripts/creategroups.py settings=settings`
para tentar inserir o DJANGO_SETTINGS_MODULE, porém da o mesmo erro.

Tentei prosseguir sem roda o comando, e deu tudo certo, porém ao executar o 
`python manage.py runserver`
e logar com a conta de adm ou a normal na qual me passaram ele da o seguinte erro:
![erro2](https://cloud.githubusercontent.com/assets/14116020/16168326/d48bfe1e-34d9-11e6-8c06-e686ca7633c5.png)

**Comment by chocoelho** [comment]
Tá, o erro possivelmente está em não ter copiado o `settings.py.DIST` para `settings.py`.

**Comment by VictorArnaud** [comment]
tem um passo no INSTALL.md que da um cp settings.py.DIST settings.py na qual eu executei, posso tentar verificar se foi copiado e se for o caso tentar copiar na mão msm, irei tentar lhe mantenho informado, vou tentar add o simião aqui tb

**Comment by chocoelho** [comment]
O Simião já tem convite pro grupo, basta só ele aceitar  
  
![](https://link.nylas.com/open/7zv5ss99rsyj5tevwqlxfyr6t/local-
4a923443-076e?r=cmVwbHkrMDAzNGNkNTM4MjdkOWYwNDJjYmZiNDg4MDIyNDNmZmYzN2IwYTBkYmRmM2M2MzdiOTJjZjAwMDAwMDAxMTM3ZWQwMDg5MmExNjljZTA5OThhY2M4QHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 19 2016, at 6:26 pm, Victor Arnaud &lt;notifications@github.com&gt;
wrote:  

> tem um passo no INSTALL.md que da um cp settings.py.DIST settings.py na qual
eu executei, posso tentar verificar se foi copiado e se for o caso tentar
copiar na mão msm, irei tentar lhe mantenho informado, vou tentar add o simião
aqui tb

>

> —  
> You are receiving this because you commented.  
> Reply to this email directly, [view it on GitHub](https://github.com/caep-
unb/gestorpsi/issues/82#issuecomment-227021255&r=cmVwbHkrMDAzNGNkNTM4MjdkOWYwNDJjYmZiNDg4MDIyNDNmZmYzN2IwYTBkYmRmM2M2MzdiOTJjZjAwMDAwMDAxMTM3ZWQwMDg5MmExNjljZTA5OThhY2M4QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/ADTNU8P1A8HWP7ZqrmykAXZwXP_ldXmBks5qNbQIgaJpZM4I413C&r=cmVwbHkrMDAzNGNkNTM4MjdkOWYwNDJjYmZiNDg4MDIyNDNmZmYzN2IwYTBkYmRmM2M2MzdiOTJjZjAwMDAwMDAxMTM3ZWQwMDg5MmExNjljZTA5OThhY2M4QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/ADTNU1rY8oLUwTxKIdg0YH4jEf3kYqUIks5qNbQIgaJpZM4I413C.gif)

**Comment by VictorArnaud** [comment]
tem alguma ideia do porque que o servidor está dando 500 internal server erro?? tirando aquela parte do scripts/creategroups.py que deu erro, o ambiente já ta subido aqui, só não consigo conectar ao servidor devido esse erro.
